name: quran_radio
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.46
  just_audio_background: ^0.0.1-beta.10
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.1.3
  syncfusion_flutter_gauges: ^28.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  android: true
  ios: false
  color: "#121212"
  android_12:
    color: "#121212"
    image: null
